### ISSUE TITLE
Difference between GROBID and Sciencebeam-parser

### ISSUE THREAD

**Issue by Apurv3377** [eLifePathways/sciencebeam-parser#466]
First of all, Sorry for opening a bug.  I would like to know about some general point about the Python GROBID and sciencebeam-parser. 

Currently sciencebeam-parser only have GROBID intergration, are there any differences in terms of the structure extraction in sciencebeam-parser and GROBID? 

Is there any possibility of integration of Table/Figure Extraction tool in sciencebeam-parser so that It can be improved further?

I am performing an Benchmark for various Information Extraction Tools, And I would like to include sciencebeam-parser into my work If it performs differently than GROBID. 

Thanks.

**Comment by de-code** [comment]
Hi @Apurv3377 thank you for raising the question. It is a good question indeed.

Previously we were working very closely with GROBID and around it.
As such we have tools such as [sciencebeam-pipelines](https://github.com/elifesciences/sciencebeam-pipelines) (previously the `sciencebeam` repo) that adds a thin layer on top of GROBID, by adding Word support and outputting JATS XML.

We were than mainly focusing on training our own models for author submitted manuscripts (with a current focus on bioRxiv).
With that we were also invested in DL (Deep Learning) models and extended the capabilities via [sciencebeam-trainer-delft](https://github.com/elifesciences/sciencebeam-trainer-delft).

The main motivation were mainly around making it easier to extend and re-use. (I proposed a [Python port previously with GROBID](https://github.com/kermitt2/grobid/issues/568) but there wasn't that much uptake on their side)

It is true, that the initial effort on `sciencebeam-parser` was to create feature parity by integrating the GROBID models that we used and evaluated.

Shared components of ScienceBeam Parser and GROBID:

- Low-level PDF extraction via `pdfalto`
- Sequence models via `delft` (and `wapiti`)

There is no direct usage of GROBID (apart from the above components).

Some things that work differently:

- We integrated `layout-parser` to optionally use CV (Computer Vision) to detect figures (disabled by default)
- We integrated OCR (via tesseract) to match figure images on pages distant from their description (disabled by default)
- It is all written in Python (apart from the third-party components):
  - this makes it usable as a Python library without needing to run a service separately
  - individual components could be used and extended
  - adding more examples to: [sciencebeam-usage-examples](https://github.com/elifesciences/sciencebeam-usage-examples)
- Having learned from the GROBID architecture, the model structure have been redesigned to be less coupled (see [ARCHITECTURE.md](https://github.com/elifesciences/sciencebeam-parser/blob/develop/ARCHITECTURE.md)):
  - It would be easier to replace or skip models
- The output contains coordinates for almost every element (GROBID also contains coordinates for many elements)
- The output contains formatting such as bold and italic (relies on the output of `pdfalto`)
- The output contains more of the "omitted" content as notes, making it easier to identify why content is potentially missing or misclassified
- APIs support Word (`docx` etc) documents
- Response can be JATS XML (including "Asset Zip" containing JATS XML)

To respond to:

> Is there any possibility of integration of Table/Figure Extraction tool in sciencebeam-parser so that It can be improved further?

The integration of `layout-parser` is an example of that for figures. We were planning to do the same for tables. Although it would initially just include tables as images.

There is some [evaluation on bioRxiv 10k](https://github.com/elifesciences/sciencebeam-parser/wiki/bioRxiv-10k-Evaluation). Although it is not ScienceBeam Parser specifically yet.

As our focus is on author submitted manuscripts, I suspect the current models trained on bioRxiv won't achieve the top scores for typeset papers.

I have looked at available open source extraction tools before so I would be interested in your evaluation as well.

**Comment by de-code** [comment]
Hi @Apurv3377 do you feel your question has sufficiently been answered?

**Comment by Apurv3377** [comment]
Hi @de-code Thanks for taking time in explaining this.
