### ISSUE TITLE
deploy doc over azure function or other platform

### ISSUE THREAD

**Issue by wanghaisheng** [eLifePathways/sciencebeam-parser#505]
pls add,thanks for your great works

**Comment by de-code** [comment]
Thank you for raising the request.
We don't have experience with Azure functions.
It can be deployed in a Kubernetes using a Helm chart, if that works? A Helm chart is available here: https://gitlab.coko.foundation/sciencebeam/sciencebeam-charts/-/tree/develop/sciencebeam-parser (although it is lacking documentation)

Could you please raise your request in: https://gitlab.coko.foundation/sciencebeam/sciencebeam-parser/-/issues
(As the Coko Foundation is adopting ScienceBeam)
