### ISSUE TITLE
output_path parameter is not working

### ISSUE THREAD

**Issue by fabiobatalha** [eLifePathways/sciencebeam-parser#62]
XML files are always being saved in the input folder.

sciencebeam.examples.grobid_service_pdf_to_xml

**Comment by de-code** [comment]
Thank you for reporting and fixing the issue. I should probably deprecate those pipelines. I would recommend using the pipeline under `Simple Pipeline` which not only requires less code to extend but can also be served via the API as well as Apache Beam (whereas grobid_service_pdf_to_xml only works with Apache Beam).
