### ISSUE TITLE
Release versions for ScienceBeam docker images

### ISSUE THREAD

**Issue by de-code** [eLifePathways/sciencebeam-parser#82]
It seems to make sense to use release versions now that we encourage xPub to deploy their own ScienceBeam containers.

The versions could be managed like for releases of say `sciencebeam-utils`. If the version field from the package does not correspond to a git tag, perform the release. In our case push a docker image with the version.

Based on the discussions around the _libero_ project we could scope commit versioned containers with a suffix like `_unstable`. We could a bit later prune old commit versions from the current container image name.

In the future the code could be release on pypi as well but it doesn't seem useful at present.

/cc @giorgiosironi

**Comment by giorgiosironi** [comment]
> If the version field from the package does not correspond to a git tag, perform the release

And as in there, the tag will be auto-created

> we could scope commit versioned containers with a suffix like `_unstable`

IIRC that was more oriented to building pull requests (which would create all sorts of broken images), but we'll define a specific policy for PRs/`develop`/`master`/release here.

**Comment by de-code** [comment]
> IIRC that was more oriented to building pull requests (which would create all sorts of broken images), but we'll define a specific policy for PRs/`develop`/`master`/release here.

I thought that was also to not get flooded with commit tags when looking at the tags of a docker image.

**Comment by giorgiosironi** [comment]
> to not get flooded with commit tags

Also true since pagination is lacking on Docker Hub
